### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/VanCrime#45]
> **Congratulations on finishing milestone 1!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## Submission instructions
rubric={mechanics:4}

Well done!

## Section 1: Motivation and Purpose
rubric={reasoning:8,writing:2}

Well done!

## Section 2: Description of the data
rubric={reasoning:8,writing:2}

- [ ] `proposal.md` - **Dataset description section**: The level of description is the dataset is very general and it is not focusing in the variables that are important for the analysis. **-1 reasoning**

- [ ] `proposal.md` - **Dataset description section**: There is not evidence data quality analysis. Are there missing values? Are these values an important percentage of the dataset?. **-1 reasoning**

Comments:
- Your description lacks analysis of the dataset specific to your project (tasks, target group, app…). 

## Section 3: Research questions and usage scenarios
rubric={reasoning:12,writing:2}

- [ ] `proposal.md` - **Persona**: In the persona description it is not informed what is needed to visualize from the data  **-3 reasoning**

Comments: 
- The persona explains clearly what the application provides for the user but not why it is beneficial.
- It is not completely matching the [milestone instructions](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/#personas). What could be improved is the progression of steps, starting from the problem of the user that is intended to be solved by the application. 
- Also please note that Persona is a scenario and does not need to necessarily include all the application features.

## Section 4:  Description of your app & sketch
rubric={viz:10, writing:2, reasoning: 3}

Well done!

## Section 5:  Team work contract and collaborative documentation
rubric={reasoning:4}

Well done!

## Code of Conduct
rubric={reasoning:1}

Well done!

## Contribution guidelines
rubric={reasoning:1}

Well done!
